In [5]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression


In [6]:
df=pd.read_csv('book1.csv')

np.shape(df)

(13, 4)

In [7]:
df.head(5)

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [8]:
dummies = pd.get_dummies(df[['Car Model']])
dummies

Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class
0                   0                 1                                0
1                   0                 1                                0
2                   0                 1                                0
3                   0                 1                                0
4                   0                 1                                0
5                   1                 0                                0
6                   1                 0                                0
7                   1                 0                                0
8                   1                 0                                0
9                   0                 0                                1
10                  0                 0                                1
11                  0                 0                                1
12                  0                 0                                1

In [11]:
merge = pd.concat([df,dummies],axis='columns')
merge

Car Model  Mileage  Sell Price($)  Age(yrs)  \
0                  BMW X5    69000          18000         6   
1                  BMW X5    35000          34000         3   
2                  BMW X5    57000          26100         5   
3                  BMW X5    22500          40000         2   
4                  BMW X5    46000          31500         4   
5                 Audi A5    59000          29400         5   
6                 Audi A5    52000          32000         5   
7                 Audi A5    72000          19300         6   
8                 Audi A5    91000          12000         8   
9   Mercedez Benz C class    67000          22000         6   
10  Mercedez Benz C class    83000          20000         7   
11  Mercedez Benz C class    79000          21000         7   
12  Mercedez Benz C class    59000          33000         5   

    Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class  
0                   0                 1                                0  
1                   0                 1                                0  
2                   0                 1                                0  
3                   0                 1                                0  
4                   0                 1                                0  
5                   1                 0                                0  
6                   1                 0                                0  
7                   1                 0                                0  
8                   1                 0                                0  
9                   0                 0                                1  
10                  0                 0                                1  
11                  0                 0                                1  
12                  0                 0                                1

In [21]:
final = merge.drop(['Car Model','Car Model_Mercedez Benz C class','Sell Price($)'], axis ='columns')
y=df[['Sell Price($)']]
y

Sell Price($)
0           18000
1           34000
2           26100
3           40000
4           31500
5           29400
6           32000
7           19300
8           12000
9           22000
10          20000
11          21000
12          33000

In [23]:
reg = LinearRegression()
reg.fit(final,y)


LinearRegression()

In [25]:
final

Mileage  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000         6                  0                 1
1     35000         3                  0                 1
2     57000         5                  0                 1
3     22500         2                  0                 1
4     46000         4                  0                 1
5     59000         5                  1                 0
6     52000         5                  1                 0
7     72000         6                  1                 0
8     91000         8                  1                 0
9     67000         6                  0                 0
10    83000         7                  0                 0
11    79000         7                  0                 0
12    59000         5                  0                 0

In [28]:
reg.score(final,y)

0.9417050937281082

ONE HOT ENCODER

In [36]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dfle=df
dfle['Car Model']=le.fit_transform(dfle['Car Model'])

dfle

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [49]:
x=dfle.drop(['Sell Price($)'],axis='columns').values
y=dfle[['Sell Price($)']].values

In [52]:
print(x,y)

[[    1 69000     6]
 [    1 35000     3]
 [    1 57000     5]
 [    1 22500     2]
 [    1 46000     4]
 [    0 59000     5]
 [    0 52000     5]
 [    0 72000     6]
 [    0 91000     8]
 [    2 67000     6]
 [    2 83000     7]
 [    2 79000     7]
 [    2 59000     5]] [[18000]
 [34000]
 [26100]
 [40000]
 [31500]
 [29400]
 [32000]
 [19300]
 [12000]
 [22000]
 [20000]
 [21000]
 [33000]]


In [59]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features=[0])

TypeError: __init__() got an unexpected keyword argument 'categorical_features'